spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
name = "spin-outbound-http"
version = "1.0.0"

[variables]
object = { default = "teapot" }

[[trigger.http]]
route = "/hello"
component = "hello"

[component.hello]
source = "target/spin-outbound-http.wasm"
allowed_outbound_hosts = ["https://random-data-api.fermyon.app"]
[component.hello.variables]
message = "I'm a {{object}}"
[component.hello.build]
command = "npm run build"
