spin_manifest_version = 2

[application]
authors = ["Ryan Levick <ryan.levick@fermyon.com>"]
description = ""
name = "sqlite"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "sqlite"

[component.sqlite]
source = "target/sqlite.wasm"
exclude_files = ["**/node_modules"]
sqlite_databases = ["default"]
[component.sqlite.build]
command = "npm run build"
