spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
name = "spin-planetscale"
version = "1.0.0"

[[trigger.http]]
route = "/hello"
component = "planetscale"

[component.planetscale]
source = "target/spin-planetscale.wasm"
allowed_http_hosts = ["https://aws.connect.psdb.cloud"]
files = ["src/index.js"]
[component.planetscale.build]
command = "npm run build"