spin_manifest_version = 2

[application]
authors = ["Thorsten Hans <thorsten.hans@gmail.com>"]
description = "Demonstrates how to use key-value store APIs in JS"
name = "kv"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "kv"

[component.kv]
source = "target/kv.wasm"
key_value_stores = ["default"]
exclude_files = ["**/node_modules"]
[component.kv.build]
command = "npm run build"
