spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
name = "spin-http-js"
version = "1.0.0"

[[trigger.http]]
route = "/hello"
component = "hello"

[component.hello]
source = "target/spin-http-js.wasm"
[component.hello.build]
command = "npm install && npm run build"
