spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
name = "spin-simple-ssr"
version = "1.0.0"

[[trigger.http]]
route = "/hello"
component = "SSR"

[[trigger.http]]
route = "/static/..."
component = "fileserver"

[component.SSR]
source = "target/spin-simple-ssr.wasm"
allowed_http_hosts = ["https://some-random-api.ml"]
files = [{source = "src/public", destination = "/"} ]
[component.SSR.build]
command = "npm run build"

[component.fileserver]
source = "modules/spin_static_fs.wasm"
files = [{ source = "dist/static", destination = "/" }, ]
