spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
name = "spin-outbound-pg"
version = "1.0.0"

[[trigger.http]]
route = "/hello"
component = "hello"

[component.hello]
source = "target/spin-outbound-pg.wasm"
[component.hello.build]
command = "npm run build"
